### ISSUE TITLE
eslint no-async-promise-executor on lib/pa11y-ci.js:43

### ISSUE THREAD

**Issue by josebolos** [pa11y/pa11y-ci#152]
After bumping the dependencies, eslint complains about `no-async-promise-executor` on lib/pa11y-ci.js:43. From the eslint docs:

> The new Promise constructor accepts an executor function as an argument [...] The executor function can also be an async function. However, this is usually a mistake, for a few reasons:
>
> * If an async executor function throws an error, the error will be lost and won't cause the newly-constructed Promise to reject. This could make it difficult to debug and handle some errors.
> * If a Promise executor function is using await, this is usually a sign that it is not actually necessary to use the new Promise constructor, or the scope of the new Promise constructor can be reduced.

We probably want to make the `pa11yCi` function async for consistency with pa11y, and remove the additional promise if possible so the executor function doesn't need to be async.

Probably best done as part of the v3.0 release.

**Comment by danyalaytekin** [comment]
Hi @XhmikosR and @josebolos, I'm closing this issue since there's a [commit](https://github.com/pa11y/pa11y-ci/commit/1374cd7312dfc2e953981caac89822628ec59c8a) since merged to `main` here that references it, and there were releases after the conversation was last touched.  If I'm mistaken please reopen.
