### ISSUE TITLE
what are the very differences between pa11y-ci and pa11y?

### ISSUE THREAD

**Issue by andreabisello** [pa11y/pa11y-ci#175]
readying the documentation https://github.com/pa11y/pa11y-ci#pa11y-ci 
not clear what are the differences between the use of pa11y and the use of pa11y-ci
both are command line, so both can be used in ci (for example in jenkins), so what are the real benefits of pa11y-ci?
maybe we can improve documentation with other examples.
thanks

**Comment by josebolos** [comment]
Hi @andreabisello,

Thanks for creating this issue. I agree that the difference between `pa11y` and `pa11y-ci` is not clear for anyone that is not familiar already with the projects. There are several reasons for this to be the case, and I'm aware that the choice of calling the tool `pa11y-ci` doesn't help as, as you correctly state, both can be used in a CI environment.

The main difference between `pa11y` and `pa11y-ci` is that `pa11y` is only able to test one URL at a time, while `pa11y-ci` can test more than one. As a result, `pa11y-ci` supports things like reading URLs from sitemaps in order to make the task of checking several URLs easier.

Broadly speaking, the `pa11y` codebase is much better maintained, so we have been working behind the scenes for a while in order to move all the functionality of `pa11y-ci` into `pa11y` itself, with the goal of eventually deprecating `pa11y-ci`. We're still quite far away from being able to do that though so, in the meantime, we welcome any improvements to the documentation that may make things clearer.

I hope that this helps.
