### ISSUE TITLE
Using `--sitemap-exclude` command-line option.

### ISSUE THREAD

**Issue by 1jasgithub** [pa11y/pa11y-ci#182]
Hello,
how would I include the '--sitemap-exclude' command-line option with our website?

pa11y-ci keeps failing on pdfs.

I see this line in package.json
    "pa11y-ci:sitemap": "pa11y-ci --sitemap http://localhost:4000/sitemap.xml --sitemap-exclude \"/*.pdf\"  --sitemap-exclude \"/admin\""

but not sure how to use it to exclude the pdf? (I'm a new user)
Thanks!
Jas

**Comment by josebolos** [comment]
Hi @1jasgithub!

The code for excluding URLs from the testing [uses a simple regular expression](https://github.com/pa11y/pa11y-ci/blob/52fd274a16f0a1c7e57789940e216048ee21bcde/bin/pa11y-ci.js#L218-L222), so you should be able to pass any valid regular expression and pa11y-ci will match all the [URLs in the sitemap against the regexp](https://github.com/pa11y/pa11y-ci/blob/52fd274a16f0a1c7e57789940e216048ee21bcde/bin/pa11y-ci.js#L242).

As what you're passing as an argument to pa11y is a regex, the character `*` will be interpreted as "zero or more instances of the previous token" rather than a pathname wildcard. Something like the following should work to exclude PDFs:

```sh
pa11y-ci --sitemap 'http://localhost:4000/sitemap.xml' --sitemap-exclude '\.pdf$'
```
