### ISSUE TITLE
Timeout is ignored - wait for element

### ISSUE THREAD

**Issue by yansifw** [pa11y/pa11y-ci#191]
Hello!

I am trying to configure the default timeout when using wait for element. I've added the timeout option in `defaults`, `url` and `chromeLaunchConfig` sections but I still get the default timeout:

`Error: waiting for function failed: timeout 30000ms exceeded`

Is this timeout configurable? How can I increase it?

Thanks!

**Comment by josebolos** [comment]
Pa11y has a `timeout` flag/config option that allows you to specify the time in milliseconds that pa11y will wait for a test to finish before giving up.

This timeout value is for the entire test run, so that will include the time to initialise Chrome through the puppeteer library, load the page, carry any actions that have been specified, and finally run the automated accessibility test. As of pa11y 6.1.0 the default timeout is 60 seconds.

There's an additional timeout for each individual action that the browser takes, this is set by the puppeteer library and it's set to 30 seconds. Although this value can be changed in puppeteer, I don't think that this timeout is exposed in pa11y so it's not something that can be configured directly.

Some alternatives could be:

* Make the site faster so the action takes less than 30 seconds to run 😉
* Pa11y by default will create a new puppeteer instance, but you can pass it an existing puppeteer instance with a page already loaded. You could use write a short node script that starts puppeteer, executes the desired actions using puppeteer commands (with a timeout higher than 30 seconds for each of them), and then finally calls pa11y: https://github.com/pa11y/pa11y/tree/9cf10d4d511ccb0e5129495968a24b6512bfe6ee#browser-browser-and-page-page
