### ISSUE TITLE
Generate html report using pa11y-ci

### ISSUE THREAD

**Issue by dgateles** [pa11y/pa11y-ci#77]
I have multiple urls and I want to save reports to html file so that I can easily embed to Jenkins for report. Is there any way to do?

**Comment by aarongoldenthal** [comment]
If people are still looking, I started a standalone HTML reporter module (https://www.npmjs.com/package/pa11y-ci-reporter-html) a while ago for just that reason.  It creates one summary page with results for all urls scanned, and individual HTML reports for each page with the details.

**Comment by deepayadav06** [comment]
Hi @aarongoldenthal, I am trying to convert my JSON file into html but getting below error - Can you help please?
**C:\Users\DeepaYadav\Documents\pa11y-ci>pa11y-ci-reporter-html**
Error parsing JSON from file './pa11y-ci-results.json' - Unexpected token � in JSON at position 0
Fatal error - exiting (1)

**Comment by aarongoldenthal** [comment]
@deepayadav06 I would check the encoding on the JSON file.  The reporter expects UTF-8 encoding, which is standard on Linux platforms.  If you're running in Windows PowerShell (and maybe other cases), it defaults to UTF-16 (that's where I usually see this issue).

**Comment by deepayadav06** [comment]
Hi @aarongoldenthal, Thanks for your prompt reply. I have tried converting the file to UTF8 using external tools but unfortunately no luck. Can you please suggest any solution I can make inside pally-ci / how I can set UTF-8 in windows. Is there any way to set this value in .pa11yci or package.json file? Looking forward for your reply.

**Comment by aarongoldenthal** [comment]
@deepayadav06 This is unfortunately one of those places where Windows is not helpful.  Depending on your version of PowerShell, this article https://stackoverflow.com/questions/40098771/changing-powershells-default-output-encoding-to-utf-8 has details on changing the PowerShell encoding.  As noted, the default for utf8 in Windows is with UTF-8 with BOM, which also causes issues since the expectation is no BOM (again, the Linux standard).  There is a link there that gives some workarounds (if you just want to change for running pa11y-ci, it also includes options like `Get-Content path/to/file.ext | out-file -encoding ASCII targetFile.ext` which could be scripted to convert the file before generating the HTML report).  If you have Powershell 6 or later, there is a `utf8NoBOM` [encoding option](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/out-file?view=powershell-6#parameters).  If you're on PowerShell 5.1 (the default in Win10), there are [fewer encoding options](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/out-file?view=powershell-5.1#parameters), and your best bet is probably "ASCII" if that character set works.

I will take a look at options to auto-detect or explicitly specify encoding (per this issue https://gitlab.com/gitlab-ci-utils/pa11y-ci-reporter-html/-/issues/38).

**Comment by josebolos** [comment]
Thanks for creating this issue. It looks like this is now fixed, feel free to reopen the issue if not.
