### ISSUE TITLE
Documentation error for "Viewport"

### ISSUE THREAD

**Issue by AssassinLV** [pa11y/pa11y-ci#81]
```
{
    "defaults": {
        "timeout": 1000,
        "page": {
            "viewport": {
                "width": 320,
                "height": 480
            }
        }
    },
    "urls": [
        "http://pa11y.org/",
        "http://pa11y.org/contributing"
    ]
}
```

Will make the pa11y-ci to fail on not recognizing "page" object.
I made it to work putting "viewport" dirrectly under the "defaults":
```
{
    "defaults": {
        "timeout": 1000,
        "viewport": {
            "width": 320,
            "height": 480
        }
    },
    "urls": [
        "http://pa11y.org/",
        "http://pa11y.org/contributing"
    ]
}
```

**Comment by cvolpe-ecobee** [comment]
@AssassinLV Do you know if there is a way to verify that in this case, pa11y actually runs in the chosen viewport? 

The reason I ask is because I did what you have suggested above and it appeared to execute ok, but I question if it actually ran with the selected viewport.  So I purposely tried to break the config and see what would happen. For example, by changing the 'viewport' key to something bogus. Surprisingly enough, pa11y still ran. See below. There's no indication that this works, any thoughts/ideas? 

`{
    "defaults": {
        "timeout": 1000,
        "whatever": {
            "width": 320,
            "height": 480
        }
    },
    "urls": [
        "http://pa11y.org/",
        "http://pa11y.org/contributing"
    ]
}`
